# Generated by Django 3.1 on 2021-12-10 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_no', models.IntegerField(default=0)),
                ('customer_name', models.CharField(max_length=30)),
                ('type_account', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=500)),
                ('contact_no', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Image', models.ImageField(default='', upload_to='bankmanagement/images')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_no', models.IntegerField(default=0)),
                ('satus', models.CharField(max_length=15)),
                ('tdate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
